// Deterministic event-log fixtures for backend-free visual checks.
// Same array is used by src/utils/__tests__/buildCanvasState.test.ts —
// keep both in sync. All timestamps are fixed unix floats; no Date.now().
import type { EventLogEntry } from '../types'

export const FIXTURE_EVENTS: EventLogEntry[] = [
  {
    id: 1,
    timestamp: 1756000000.100,
    event_type: 'agent_spawned',
    agent_id: 'exp_a',
    parent_id: 'root',
    sim_id: 'exp_a',
    region: 'tool_tissue_boundary',
    error_before: 0.43,
    error_after: null,
    payload: { reason: 'high_error', target_region: 'tool_tissue_boundary',
               error_level: 0.43, planned_steps: 100 },
  },
  {
    id: 2,
    timestamp: 1756000005.000,
    event_type: 'agent_spawned',
    agent_id: 'exp_b',
    parent_id: 'root',
    sim_id: 'exp_b',
    region: 'upper_left',
    error_before: 0.31,
    error_after: null,
    payload: { reason: 'high_error', target_region: 'upper_left',
               error_level: 0.31, planned_steps: 100 },
  },
  {
    id: 3,
    timestamp: 1756000010.000,
    event_type: 'agent_spawned',
    agent_id: 'cap_1',
    parent_id: 'root',
    sim_id: null,
    region: null,
    error_before: null,
    error_after: null,
    payload: { reason: 'error_below_threshold', target_dof: 2 },
  },
  {
    id: 4,
    timestamp: 1756000020.000,
    event_type: 'agent_completed',
    agent_id: 'exp_a',
    parent_id: null,
    sim_id: 'exp_a',
    region: 'tool_tissue_boundary',
    error_before: 0.43,
    error_after: 0.21,          // Δ = 0.22 > 0.05 → success
    payload: { samples_collected: 100, fine_tune_loss: 0.018 },
  },
  {
    id: 5,
    timestamp: 1756000025.000,
    event_type: 'agent_failed',
    agent_id: 'exp_b',
    parent_id: null,
    sim_id: 'exp_b',
    region: 'upper_left',
    error_before: 0.31,
    error_after: null,
    payload: { error: 'timeout' },
  },
  {
    id: 6,
    timestamp: 1756000030.000,
    event_type: 'capability_unlocked',
    agent_id: 'cap_1',
    parent_id: null,
    sim_id: null,
    region: null,
    error_before: null,
    error_after: null,
    payload: { previous_dof: 1, new_dof: 2,
               trigger_error: 0.07, threshold: 0.08 },
  },
]
